# Generated by Django 5.0.3 on 2024-03-31 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_product_feature'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_feature',
            old_name='image1',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='product_feature',
            name='description',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
