# Generated by Django 5.0.3 on 2024-04-22 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_order_produk'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='produk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.produk'),
        ),
    ]
