# Generated by Django 5.0.3 on 2024-03-31 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_product_feature_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_feature',
            name='Category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='home.category'),
        ),
    ]
