# Generated by Django 5.0.3 on 2024-04-25 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_orderitem_produk'),
    ]

    operations = [
        migrations.AddField(
            model_name='produk',
            name='digital',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
