# Generated by Django 5.0.3 on 2024-04-25 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_produk_digital'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='address1',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='address2',
        ),
    ]
