# Generated by Django 5.0.3 on 2024-03-31 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_product_feature_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_feature',
            name='image',
            field=models.ImageField(upload_to='uploads/products_features/'),
        ),
    ]
