# Generated by Django 5.0.1 on 2024-03-31 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_order_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='Category',
        ),
    ]
