# Generated by Django 5.0.1 on 2024-04-01 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_remove_order_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_feature',
            name='image',
            field=models.ImageField(upload_to='uploads/product_features/'),
        ),
    ]
