# Generated by Django 5.0.1 on 2024-04-02 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_product_feature_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_feature',
            name='digital',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
