# Generated by Django 5.0.1 on 2024-04-03 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_testimonials_bestsells_blog_newarrival_toprated_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonials',
            old_name='description',
            new_name='description1',
        ),
        migrations.AddField(
            model_name='testimonials',
            name='description2',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
