# Generated by Django 5.0.1 on 2024-04-03 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_rename_description_blog_blogtitle_blog_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='cta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seasonname', models.CharField(max_length=200)),
                ('startingprice', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('image', models.ImageField(upload_to='uploads/cta/')),
                ('discount', models.DecimalField(decimal_places=0, default=0, max_digits=3)),
            ],
        ),
    ]
